export const CATEGORIES = [
  "city",
  "nature",
  "culture",
  "coast",
  "mountain",
] as const;

export type Category = (typeof CATEGORIES)[number] | "search" | "pin";

export type Place = {
  id: string;
  name: string;
  region: string;
  blurb: string;
  category: Category;
  lat: number;
  lng: number;
  zoom: number;
};

export const CATEGORY_LABEL: Record<Category, string> = {
  city: "City",
  nature: "Nature",
  culture: "Culture",
  coast: "Coast",
  mountain: "Mountain",
  search: "Search",
  pin: "Pin",
};

export const HOME: Place = {
  id: "prime-meridian",
  name: "Prime Meridian",
  region: "Greenwich, London",
  blurb: "The line that split the world into hemispheres. East meets west on this quiet hill above the Thames.",
  category: "culture",
  lat: 51.4778,
  lng: -0.0015,
  zoom: 13,
};

export const DESTINATIONS: Place[] = [
  HOME,
  {
    id: "kyoto",
    name: "Fushimi Inari",
    region: "Kyoto, Japan",
    blurb: "Thousands of vermilion gates climb the mountain, each one a wish left standing.",
    category: "culture",
    lat: 34.9671,
    lng: 135.7727,
    zoom: 14,
  },
  {
    id: "oia",
    name: "Oia",
    region: "Santorini, Greece",
    blurb: "Whitewashed cliffs over a drowned caldera. The Aegean at its most theatrical.",
    category: "coast",
    lat: 36.4618,
    lng: 25.3753,
    zoom: 14,
  },
  {
    id: "paine",
    name: "Torres del Paine",
    region: "Patagonia, Chile",
    blurb: "Granite towers, wind, and water the color of glacial milk. The south at full volume.",
    category: "nature",
    lat: -50.9423,
    lng: -73.4068,
    zoom: 10,
  },
  {
    id: "marrakech",
    name: "Jemaa el-Fnaa",
    region: "Marrakech, Morocco",
    blurb: "A square that becomes a city after dusk: steam, drums, and orange-wood smoke.",
    category: "city",
    lat: 31.6258,
    lng: -7.9891,
    zoom: 15,
  },
  {
    id: "skogafoss",
    name: "Skógafoss",
    region: "South Coast, Iceland",
    blurb: "A curtain of meltwater on the old sea cliffs. Walk the spray and keep going east.",
    category: "nature",
    lat: 63.5321,
    lng: -19.5114,
    zoom: 13,
  },
  {
    id: "manhattan",
    name: "Midtown",
    region: "New York, USA",
    blurb: "A grid that never quite sleeps. Look up — the skyline is the map.",
    category: "city",
    lat: 40.758,
    lng: -73.9855,
    zoom: 13,
  },
  {
    id: "venice",
    name: "San Marco",
    region: "Venice, Italy",
    blurb: "A city drawn in water. Stone, tide, and a piazza that has seen every century in.",
    category: "city",
    lat: 45.434,
    lng: 12.3388,
    zoom: 15,
  },
  {
    id: "machu-picchu",
    name: "Machu Picchu",
    region: "Cusco, Peru",
    blurb: "A citadel in the clouds, held by terraces and silence. Arrive before the day does.",
    category: "culture",
    lat: -13.1631,
    lng: -72.545,
    zoom: 14,
  },
  {
    id: "louise",
    name: "Lake Louise",
    region: "Banff, Canada",
    blurb: "A turquoise bowl under the Rockies. Canoes look like punctuation on the water.",
    category: "mountain",
    lat: 51.4254,
    lng: -116.1773,
    zoom: 13,
  },
  {
    id: "table-mountain",
    name: "Table Mountain",
    region: "Cape Town, South Africa",
    blurb: "A flat-topped sentinel over two oceans. The city gathers at its feet.",
    category: "mountain",
    lat: -33.9628,
    lng: 18.4098,
    zoom: 12,
  },
  {
    id: "shibuya",
    name: "Shibuya Crossing",
    region: "Tokyo, Japan",
    blurb: "The world's most famous pause. Then everyone moves at once.",
    category: "city",
    lat: 35.6595,
    lng: 139.7004,
    zoom: 16,
  },
  {
    id: "eiffel",
    name: "Champ de Mars",
    region: "Paris, France",
    blurb: "Iron lace against a wide lawn. The tower is only half the view.",
    category: "city",
    lat: 48.8584,
    lng: 2.2945,
    zoom: 15,
  },
  {
    id: "petra",
    name: "The Treasury",
    region: "Petra, Jordan",
    blurb: "A façade carved from rose stone, waiting at the end of a long, cool siq.",
    category: "culture",
    lat: 30.3225,
    lng: 35.4513,
    zoom: 15,
  },
  {
    id: "geiranger",
    name: "Geirangerfjord",
    region: "Møre og Romsdal, Norway",
    blurb: "Waterfalls thread the cliffs. The ferry feels like the only moving thing.",
    category: "coast",
    lat: 62.1015,
    lng: 7.2056,
    zoom: 11,
  },
  {
    id: "alfama",
    name: "Alfama",
    region: "Lisbon, Portugal",
    blurb: "Tram rails, tiled façades, and the river widening toward the Atlantic.",
    category: "city",
    lat: 38.7126,
    lng: -9.13,
    zoom: 15,
  },
  {
    id: "grand-canyon",
    name: "South Rim",
    region: "Arizona, USA",
    blurb: "A wound in the plateau so old it reads as a country of its own.",
    category: "nature",
    lat: 36.0544,
    lng: -112.1401,
    zoom: 12,
  },
  {
    id: "marina-bay",
    name: "Marina Bay",
    region: "Singapore",
    blurb: "A harbour remade as a garden. Light on water, and the city behind it.",
    category: "city",
    lat: 1.2834,
    lng: 103.8607,
    zoom: 15,
  },
  {
    id: "positano",
    name: "Positano",
    region: "Amalfi Coast, Italy",
    blurb: "Houses stacked like a landslide of color, catching the Tyrrhenian light.",
    category: "coast",
    lat: 40.628,
    lng: 14.485,
    zoom: 14,
  },
  {
    id: "zermatt",
    name: "Zermatt",
    region: "Valais, Switzerland",
    blurb: "Car-free streets under the Matterhorn. The peak is a compass needle.",
    category: "mountain",
    lat: 46.0207,
    lng: 7.7491,
    zoom: 13,
  },
  {
    id: "havana",
    name: "Malecón",
    region: "Havana, Cuba",
    blurb: "A seawall built for lingering. Spray, chrome, and the Gulf Stream just offshore.",
    category: "coast",
    lat: 23.1416,
    lng: -82.3519,
    zoom: 14,
  },
  {
    id: "sapa",
    name: "Sa Pa",
    region: "Lào Cai, Vietnam",
    blurb: "Rice terraces folded into the Hoàng Liên mountains, green on green.",
    category: "mountain",
    lat: 22.3364,
    lng: 103.844,
    zoom: 12,
  },
  {
    id: "dubrovnik",
    name: "Old Town",
    region: "Dubrovnik, Croatia",
    blurb: "Marble streets inside limestone walls, the Adriatic knocking at the gates.",
    category: "coast",
    lat: 42.6404,
    lng: 18.1081,
    zoom: 15,
  },
  {
    id: "uyuni",
    name: "Salar de Uyuni",
    region: "Potosí, Bolivia",
    blurb: "The world's largest mirror, when the rains come. Sky and salt trade places.",
    category: "nature",
    lat: -20.1338,
    lng: -67.4891,
    zoom: 9,
  },
  {
    id: "chefchaouen",
    name: "Chefchaouen",
    region: "Rif Mountains, Morocco",
    blurb: "A blue medina in a green fold of the Rif. Every alley is a quieter shade.",
    category: "city",
    lat: 35.1688,
    lng: -5.2636,
    zoom: 15,
  },
  {
    id: "yosemite",
    name: "Yosemite Valley",
    region: "California, USA",
    blurb: "Granite walls, a river, and light that makes the valley feel staged.",
    category: "nature",
    lat: 37.7459,
    lng: -119.5936,
    zoom: 12,
  },
  {
    id: "edinburgh",
    name: "Old Town",
    region: "Edinburgh, Scotland",
    blurb: "A ridge of stone and wynds, castle at one end, palace at the other.",
    category: "city",
    lat: 55.9486,
    lng: -3.1915,
    zoom: 14,
  },
  {
    id: "luang-prabang",
    name: "Luang Prabang",
    region: "Laos",
    blurb: "Temples at the confluence of two rivers. Dawn belongs to the monks.",
    category: "culture",
    lat: 19.886,
    lng: 102.135,
    zoom: 14,
  },
  {
    id: "cappadocia",
    name: "Göreme",
    region: "Cappadocia, Turkey",
    blurb: "A landscape hollowed into dwellings. Balloons lift off like punctuation at sunrise.",
    category: "culture",
    lat: 38.6431,
    lng: 34.8283,
    zoom: 12,
  },
  {
    id: "queenstown",
    name: "Queenstown",
    region: "Otago, New Zealand",
    blurb: "A lake town under The Remarkables. The Southern Alps do what the name promises.",
    category: "mountain",
    lat: -45.0312,
    lng: 168.6626,
    zoom: 12,
  },
];

export function placeKey(lat: number, lng: number) {
  return `${lat.toFixed(5)},${lng.toFixed(5)}`;
}
